### ISSUE TITLE
Initial thoughts

### ISSUE THREAD

**Issue by chandlerprall** [elastic/next-eui-starter#1]
In no particular order

* I like how you handled theme switching
* I'd prefer to see `Chrome` refactored into multiple function components
* The `style` prop passed to `EuiHeaderSectionItem` in `Chrome` should probably be moved to the scss file and referenced with a `className`, to match the existing pattern.
* The `MyComponent` link ("Go to page 2") throws a React warning as `NextJsLink` adds a ref to its children. Is there a way to programatically trigger navigations in Next similar to https://github.com/elastic/eui/blob/master/wiki/react-router.md#2-adapter-component ?

**Comment by pugnascotia** [comment]
Repo is now public.

**Comment by pugnascotia** [comment]
You can now use the Next starter on CodeSandbox - simply visit:

https://codesandbox.io/s/github/elastic/next-eui-starter

This was actually a complete faff, because CodeSandbox has a limit on the number of files in any repository that you import, and using `/docs` for GitHub pages meant that CodeSandbox would fail to import the repository. So now we use the `gh-pages` branch for the static export to GitHub, which meant changing how `yarn build-docs` works.

I've added links in the starter's index page and the project's README.
