### ISSUE TITLE
Update to EUI version 31

### ISSUE THREAD

**Issue by jylin** [elastic/next-eui-starter#24]
It looks like this starter is not on the latest version of EUI. Would it be possible to update to version 31?

**Comment by cchaos** [comment]
Hi 👋  @jylin. Yeah we're not great and keeping these starters up to date, and we should probably state as such 😆 . We have an internal task to consider how to make this maybe more automated. But it might be a while, as the main library is our priority.

You should be able to update your fork/usage to the latest. Otherwise, you're also welcome to send a PR this way with an upgrade.
