### ISSUE TITLE
EuiNavDrawer isLocked prop does not shift main content to the right

### ISSUE THREAD

**Issue by nandorojo** [elastic/next-eui-starter#5]
# What

When you pass `isLocked` to the `EuiNavDrawer`, you expect the drawer to be stuck and expanded, as explained by [this PR](https://github.com/elastic/eui/pull/2247) and [on this forum post](https://discuss.elastic.co/t/onislockedupdate-props-is-not-getting-called-on-every-click-of-collapse-section-in-left-navigation/216823/4). 

When expanded, the nav drawer should shift the main page content to the right, rather than having the nav drawer overlay the page content.

However, the content does not shift over. Instead, the nav drawer is fixed on top of the page.

# Expected Behavior

It should look like [this](https://discuss.elastic.co/t/onislockedupdate-props-is-not-getting-called-on-every-click-of-collapse-section-in-left-navigation/216823/4):

![bdb783a8310fd42436d99148302a60d953c74505_2_480x1000](https://user-images.githubusercontent.com/13172299/82069489-5e0c8000-96a1-11ea-9ecf-4a8110f926b9.png)

# Actual Behavior

It actually looks this:

<img width="514" alt="Screen Shot 2020-05-15 at 11 44 26 AM" src="https://user-images.githubusercontent.com/13172299/82069530-6fee2300-96a1-11ea-9eb9-fb7c0379e216.png">

# Reproducible Example

- Open this repository's example on Code Sandbox
- Open `src/components/chrome/index.tsx` and pass `isLocked` prop to the `EuiNavDrawer`

Thanks for the great work on this. Looking forward to hearing back from you!

**Comment by cchaos** [comment]
Hi @nandorojo! 

The **EuiNavDrawer** by design does not automatically shift content based on the `isLocked` status. This must be handled by the consuming application, you can see how this is handled in the docs example by looking at the `.euiNavDrawerPage__pageBody` selector.

However, we will soon be deprecating EuiNavDrawer for [EuiCollapsibleNav](https://elastic.github.io/eui/#/navigation/collapsible-nav) which will help with automatically shifting body content based on locked state.

---


**Note:** This repo is specifically for the Next-JS starter and not where we actually develop EUI. If you need to submit more component-specific issues, I'd recommend doing so in https://github.com/elastic/eui

**Comment by pugnascotia** [comment]
Thanks @cchaos. So technically there's nothing to fix for this issue, however I'll leave it open until I've updated the starter to use `EuiCollapsibleNav`.

**Comment by nandorojo** [comment]
Got it, thank you both for the help! I’ll try out `EuiCollapsibleNav` instead. 

Big fan of your work, thanks for an awesome library.

**Comment by pugnascotia** [comment]
So it turns out `EuiCollapsibleNav` needs updating to work with SSR first. Hey ho.

**Comment by nandorojo** [comment]
I can close this for now and just lazy-load in `EuiCollapsibleNav`. Thanks again.
